juandape/frontend-topv29-restaurantes

src/components/formaddfood/Addfood.css
src/components/formaddfood/Addfood.jsx
src/pages/home/Home.jsx

formaddfood

---

src/pages/about/About.jsx
src/pages/about/about.css
src/pages/commingsoon/Commingsoon.jsx
src/pages/commingsoon/commingsoon.css
src/router/index.jsx

[//]: <> muestra la pagina comming soon
[//]: <> ver vercel
[//]: <>

feat: comming soon page

---

package-lock.json
src/components/easybook/Easybook.jsx
src/components/easybook/easybook.css
src/pages/home/Home.jsx

[//]: <> componente para el home easy booking
[//]: <> ver despliegue en vercel
[//]: <>![image](https://github.com/juandape/frontend-topv29-restaurantes/assets/41099211/aa751c9f-afc1-4b18-80e2-84ea1ee4bffb)

Easy booking home page

---

src/components/access/Access.jsx
src/components/access/access.css
src/components/header/Header.jsx
src/components/header/header.css
src/router/index.jsx

[//]: <> acceso a formulario de registro o login de usuarios
[//]: <> ver en vercel
[//]: <> ![image](https://github.com/juandape/frontend-topv29-restaurantes/assets/41099211/5193bde2-bfa4-48c3-b93c-e2457f3e04a1)

mejora a componente de acceso a usuarios

---

src/components/bestfood/Bestfood.jsx
src/components/bestfood/bestfood.css
src/pages/home/Home.jsx

[//]: <> componente para el home descarga app
[//]: <>ver despliegue vercel
[//]: <>

componente para descargar app

---

src/components/formAdd/FormAdd.test.jsx

addfoodtest

---

src/components/filtercategory/FilterCat.test.jsx

Test del filtro de categorías de los restaurantes.
[//]: <> (Como te sientes con este PR? la solución que entregas como te hace sentir?)

feat:testupdatecategory

---

src/components/access/access.css

[//]: <> corrige la posicion de los accesos de login y register en modo responsive
[//]: <> probar en vercel en modo responsive icono de acceso
[//]: <>

fix: access css responsive

---

src/components/cardrest/Cardrest.css

fix:css cardrest

---

src/components/Footer/Footer.css
src/components/Footer/Footer.jsx

Se realiza el ajuste del footer en responsive, 

fix: footer responsive

---

src/components/booking/Booking.jsx
src/components/booking/booking.css
src/components/cardrest/Cardrest.css
src/components/cardrest/Cardrest.jsx
src/components/foodtypefilter/Foodtypefilter.jsx
src/components/loginform/Loginform.jsx
src/pages/home/Home.jsx
src/router/index.jsx

[//]: <> componente para hacer reserva en cada restaurante
[//]: <> dar click en restaurantes, seleccionar un restaurante, dar click a 'book a table' en en menu
[//]: <>

componente reserva en restaurantes

---

src/components/header/Header.jsx
src/components/header/header.css
src/components/international/International.jsx
src/components/international/international.css

[//]: <> agrega al header las opciones de moneda e idioma
[//]: <> ver en vercel en el header
[//]: <>

International options en header

---

src/components/bestrestaurants/BestRestaurants.jsx
src/components/bestrestaurants/bestrestaurants.css
src/pages/home/Home.jsx
src/pages/home/home.css

[//]: <> filtro en el home para restaurantes de calificacion igual o mayor a 4.5
[//]: <> ver en vercel, en el home Top Restaurants
[//]: <>

filtro top restaurants

---

src/main.jsx
src/store/actions.js
src/store/index.jsx
src/store/reducer.js
src/store/types.js

[//]: <> configuracion inicial del context
[//]: <> ver en vercel,  abrir inspeccionar del navegador, y luego verificar en componentes

montaje del context

---

package-lock.json
package.json
src/components/header/Header.jsx
src/components/loginform/Loginform.jsx
src/store/actions.js
src/store/index.jsx
src/store/reducer.js
src/store/types.js

ajuste de register User, sale email del user 

Feature register name

---

src/components/header/Header.jsx
src/components/loginform/Loginform.jsx
src/main.jsx

se ajusta el login para que funcione con localStorage
datos de ingreso:
guialexander@gmail.com
contraseña 12345
"email": "juan.pe@gmail.com",
"password": "12345"
"email": "Miguel@gmail.com",
"password": "12345"

feat: localstorage dat login

---

db.json

Se hacen correcciones en los vínculos de las imágenes, para traerlas desde Cloudinary.

feat:addedimg

---

src/components/restaurantfilter/Restaurantfilter.jsx
src/components/restbyname/Restbyname.jsx
src/components/restbyname/restbyname.css
src/router/index.jsx

Namefilter

---

.github/workflows/ci.yml
db.json
package-lock.json
package.json
src/components/navbarcardrest/Navbarcardrest.jsx
src/components/restgallery/Restgallery.jsx
src/components/restgallery/restgallery.css

[//]: <> carrusel de fotos de cada restaurante

feat: photo gallery

---

src/components/loginform/Loginform.jsx
src/components/registerform/Registerform.jsx
src/pages/sign/VerifyAccount.jsx

se realiza la page de activar la cuenta y quedar logueado,
crear un usuario en la parte de regitrar , luego va llegar un email donde al dar click validar va enviar a la pagina y va quedar logueado.

feat: verificación de la cuenta y que quede logueado

---

src/components/formAddRest/FormAddRest.jsx
src/components/formedit/FormEdit.jsx

feat: add restaurant

---

src/components/editfood/Editfood.jsx
src/components/formaddfood/Addfood.jsx
src/services/index.js

se ajusta el formulario de crear food ant edit food 
- [x ] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)

Feature createfood

---

src/components/editfood/Editfood.jsx
src/components/editfood/editfood.css

creación de button delete food

feat: button delete food

---

src/components/formaddfood/Addfood.jsx

Foodnewnew

---

src/components/editfood/Editfood.jsx
src/components/editformrestaurant/Editformrestaurant.jsx
src/components/formAddRest/FormAddRest.jsx
src/components/formaddfood/Addfood.jsx
src/components/uploaderForm/uploader.css
src/components/uploaderForm/uploader.jsx

Componente global de subida de archivos a clodinary sin enviar la imagen a el backend

feat:images

---

src/components/editfood/Editfood.jsx

feat: restaurantAndFood

---

src/components/uploaderForm/uploader.jsx

feat:linkupdate
